#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: C:\projects\nyami-github-io

# environment variables
environment:
  access_token:
    secure: 7a8U84UtyTi2/zk6aRcx0MqRcTx55u9q0A16UqsmijNXVQJ7EAAyQeKiFc4CUEUg

# Branches to build
branches:
  # Whitelist
  only:
    - source

#---------------------------------#
#       build configuration       #
#---------------------------------#

install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem
  - SET SSL_CERT_FILE=%APPVEYOR_BUILD_FOLDER%\cacert.pem
  - set PATH=C:\Ruby23\bin;%PATH%

build_script:

  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "nyami@hotmail.com"
  - git config --global user.name "Douglas Cameron"

  - cmd: gem install bundler
  - cmd: bundle install
  - cmd: if not exist _deploy (git clone https://github.com/nyami/nyami.github.io.git _deploy)
  - cmd: cd _deploy
  - cmd: git checkout master
  - cmd: cd ..
  - cmd: rake generate
  - cmd: rake deploy

test: off

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/

cache:
  - C:\Ruby23\lib\ruby\gems\2.3.0
  - C:\Ruby23\bin
